### ISSUE TITLE
Build broken: stray extra `);` in mail.service.ts (from PR #210)

### ISSUE THREAD

**Issue by suryanavv** [oblien/openship#213]
## What's broken

`apps/api/src/modules/mail/mail.service.ts` has a stray extra `);` that breaks the TypeScript compile for the entire `@repo/api` package:

```
src/modules/mail/mail.service.ts(390,5): error TS1128: Declaration or statement expected.
```

## Where it came from

Introduced in 9d580ba ("fix(security): prevent command injection in mail provisioning and SSRF via webhook URLs", merged via #210).

## The bad code

```ts
// apps/api/src/modules/mail/mail.service.ts:385-394
  if (hasEntry) {
    const pattern = `^127\\.0\\.1\\.1.*${mailDomain}`;
    const correctStr = await exec.exec(
      `grep -c ${sq(pattern)} /etc/hosts || echo 0`,
    );
    );                                                  // <-- stray extra closing paren + semicolon
    if (parseInt(correctStr.trim(), 10) > 0) {
```

## Fix

Delete the duplicate `);` on line 390.

## Impact

`bunx tsc --noEmit` (and `bun run --filter=@repo/api lint`) fails on `main` right now — blocks anyone verifying a clean typecheck on the API package.

**Comment by Hydralerne** [comment]
on it

**Comment by Hydralerne** [comment]
please create dedicated pr for only the issue, as the SSRF already solved in the https://github.com/oblien/openship/pull/212

**Comment by Hydralerne** [comment]
fixed
