### ISSUE TITLE
Build broken: available-version.test.ts uses serviceManager "openrc" not in SystemServiceManager (from PR #194)

### ISSUE THREAD

**Issue by suryanavv** [oblien/openship#214]
## What's broken

`packages/adapters/src/system/available-version.test.ts` fails `tsc --noEmit` (and `bun run --filter=@repo/adapters lint`):

```
src/system/available-version.test.ts(38,26): error TS2322: Type '"openrc"' is not assignable to type 'SystemServiceManager'.
```

## Where it came from

Introduced in e1f57ad ("fix(adapters): apk update probe reads repo URL as the version", merged via #194).

## The mismatch

`available-version.test.ts` defines a fixture:

```ts
const APK: EnvironmentProfile = {
  os: "linux", arch: "amd64", distro: "alpine",
  packageManager: "apk", serviceManager: "openrc", isRoot: true, canSudo: false,
};
```

but `SystemServiceManager` (packages/adapters/src/system/environment.ts:9) only allows:

```ts
export type SystemServiceManager = "systemd" | "launchd" | "none";
```

`"openrc"` (Alpine's init system, matching the Alpine/apk fixture this test is modeling) isn't a member.

## Fix

Either widen `SystemServiceManager` to include `"openrc"` if the codebase is meant to model Alpine hosts, or change the test fixture to use `"none"`/a supported value if `openrc` detection isn't actually implemented yet.

## Impact

`bunx tsc --noEmit` / `bun run --filter=@repo/adapters lint` fails on `main` right now. The test itself passes at runtime (vitest doesn't type-check), so this only shows up under `tsc`/lint, which is likely why it slipped through CI review.

**Comment by Hydralerne** [comment]
fixed
